spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5332/raynet
    username: raynet
    password: hesloveslo
  profiles:
    active: api, mail
logging:
  level:
    org.springframework.web: DEBUG
    cz.raynet.csvimporter: TRACE
